/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CheckFile */

#ifndef _Included_CheckFile
#define _Included_CheckFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CheckFile
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CheckFile_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
